export const TIMEZONE_OPTIONS = [
  { label: '🇰🇷 서울 (KST, UTC+9)',         short: 'KST (UTC+9)',   value: 'Asia/Seoul' },
  { label: '🇯🇵 도쿄 (JST, UTC+9)',           short: 'JST (UTC+9)',   value: 'Asia/Tokyo' },
  { label: '🇨🇳 베이징 (CST, UTC+8)',         short: 'CST (UTC+8)',   value: 'Asia/Shanghai' },
  { label: '🇸🇬 싱가포르 (SGT, UTC+8)',       short: 'SGT (UTC+8)',   value: 'Asia/Singapore' },
  { label: '🇹🇭 방콕 (ICT, UTC+7)',           short: 'ICT (UTC+7)',   value: 'Asia/Bangkok' },
  { label: '🇮🇳 뭄바이 (IST, UTC+5:30)',      short: 'IST (UTC+5:30)', value: 'Asia/Kolkata' },
  { label: '🇦🇪 두바이 (GST, UTC+4)',         short: 'GST (UTC+4)',   value: 'Asia/Dubai' },
  { label: '🇷🇺 모스크바 (MSK, UTC+3)',       short: 'MSK (UTC+3)',   value: 'Europe/Moscow' },
  { label: '🇫🇷 파리 (CET/CEST)',             short: 'CET/CEST',      value: 'Europe/Paris' },
  { label: '🇬🇧 런던 (GMT/BST)',              short: 'GMT/BST',       value: 'Europe/London' },
  { label: '🇧🇷 상파울루 (BRT, UTC-3)',       short: 'BRT (UTC-3)',   value: 'America/Sao_Paulo' },
  { label: '🇺🇸 뉴욕 (ET)',                  short: 'ET',            value: 'America/New_York' },
  { label: '🇺🇸 시카고 (CT)',                short: 'CT',            value: 'America/Chicago' },
  { label: '🇺🇸 덴버 (MT)',                  short: 'MT',            value: 'America/Denver' },
  { label: '🇺🇸 로스앤젤레스 (PT)',          short: 'PT',            value: 'America/Los_Angeles' },
  { label: '🇦🇺 시드니 (AEST/AEDT)',         short: 'AEST/AEDT',     value: 'Australia/Sydney' },
  { label: '🇳🇿 오클랜드 (NZST/NZDT)',       short: 'NZST/NZDT',     value: 'Pacific/Auckland' },
];
